stages:
  - build
  - test
  - deploy

# ------------------------------------------------------------------------------
#                                       BUILD
# ------------------------------------------------------------------------------
build:
  stage: build
  script:
    - echo "Build project..."
  only:
    - branches

# ------------------------------------------------------------------------------
#                                       TEST
# ------------------------------------------------------------------------------
test:
  stage: test
  script: echo "TODO Running tests..."
  only:
    - branches

# ------------------------------------------------------------------------------
#                               DEPLOY TO PRODUCTION
# ------------------------------------------------------------------------------
# @see http://articles.slicehost.com/2007/10/10/rsync-exclude-files-and-folders
deploy to mater:
  stage: deploy
  variables:
    DEPLOY_PATH: /var/www/litefinance-frontend-v2
  script:
    - pwd
    - if [ ! -d $DEPLOY_PATH ]; then mkdir $DEPLOY_PATH; fi
    - rsync -arvz --include-from './rsync-include.txt' --exclude-from './rsync-exclude.txt' --delete ./ $DEPLOY_PATH
    - cd $DEPLOY_PATH
    - pwd
    - node -v
    - npm install --production
    - npm run build --universal
    - npm run stop
    - npm run prod
  environment:
    name: master
    url: https://litefinance.com
  only:
    - master

# ------------------------------------------------------------------------------
#                         DEPLOY TO DEVELOPMENT (@TODO)
# ------------------------------------------------------------------------------
deploy to develop:
  stage: deploy
  variables:
    DEPLOY_PATH: /var/www/dev.litefinance-frontend-v2
  script:
    - pwd
    - if [ ! -d $DEPLOY_PATH ]; then mkdir $DEPLOY_PATH; fi
    - rsync -arvz --include-from './rsync-include.txt' --exclude-from './rsync-exclude.txt' --delete ./ $DEPLOY_PATH
    - cd $DEPLOY_PATH
    - pwd
    - node -v
    - npm install
    - npm run build --universal
    - npm run stop
    - npm run prod
  environment:
    name: develop
    url: https://dev.litefinance.com
  only:
    - develop
